services:
  ai-driven-development-labs:
    container_name: ai-driven-development-labs
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "http.server", "8000"]
    env_file:
      - .env
    environment:
      PROJECT_NAME: hello
    ports:
      - "8000:8000"
